// Per-area dictionaries. English is bundled; other languages load on demand.
// Locale loaders are listed in ./locales.ts (generated by scripts/gen-i18n-areas.ts).
import type { Dict } from "../../translate";
import ui from "./ui/en";
import enums from "./enums/en";
import facility from "./facility/en";
import expense from "./expense/en";
import po from "./po/en";
import tasks from "./tasks/en";
import settings from "./settings/en";
import shared from "./shared/en";
import platform from "./platform/en";
import publicArea from "./public/en";

export const AREAS = ["ui", "enums", "facility", "expense", "po", "tasks", "settings", "shared", "platform", "public"] as const;

export const englishAreas: Dict[] = [ui, enums, facility, expense, po, tasks, settings, shared, platform, publicArea] as Dict[];
