// Writes src/lib/i18n/messages/areas/locales.ts: one lazy loader per area for
// every language file that exists (areas/<area>/<code>.ts).
// Usage: npx tsx scripts/gen-i18n-areas.ts
import { existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { LOCALES } from "../src/lib/i18n/config";
import { AREAS } from "../src/lib/i18n/messages/areas";

const dir = join(import.meta.dirname, "../src/lib/i18n/messages/areas");
const lines = ["// Generated by scripts/gen-i18n-areas.ts: do not edit by hand.", 'import type { Dict } from "../../translate";', "", "export const areaLoaders: Record<string, (() => Promise<{ default: Dict }>)[]> = {"];
for (const { code } of LOCALES) {
  if (code === "en") continue;
  const present = AREAS.filter((a) => existsSync(join(dir, a, `${code}.ts`)));
  lines.push(`  ${code}: [${present.map((a) => `() => import("./${a}/${code}")`).join(", ")}],`);
}
lines.push("};", "");
writeFileSync(join(dir, "locales.ts"), lines.join("\n"));
console.log("wrote locales.ts");
